### ISSUE TITLE
mongorestore: command not found

### ISSUE THREAD

**Issue by EricTing** [wolferian/wolferx-chef-repo#4]
On AWS EC2 RedHat, following the guidelines to deploy the development environment, everything went well until  the command `mongorestore ~/chef-repo/wolfer_schema/mongodb/newedenfaces.bson -d wolferweb -c characters`.

The error is:
`-bash: mongorestore: command not found`

**Comment by chenfanggm** [comment]
That is because we take out wolferweb from the build process, which includes mongodb cookbook as dependency.

**Comment by wolferian** [comment]
Read.Me has updated
